version: 2
jobs:
  build:
    filters:
      branches:
        only: master
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
      - run: sudo npm install -g npm@latest
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - run: npm run build-prod
  deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project
    steps:
      - run: npm run deploy --token=$FIREBASE_TOKEN --non-interactive
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
