version: 2

# List of jobs
jobs:
  # The build job
  build:
    filters:
      branches:
        only: master
    working_directory: ~/project
    docker:
      - image: "circleci/node:latest"
    steps:
      # Steps to be added
      - checkout

      - restore_cache:
        keys:
          - node-modules-{{ checksum "package.lock.json" }}

      - run: sudo npm install -g npm@latest
      - run: npm install

      - save_cache:
        key: node-modules-{{ checksum "package.lock.json" }}
        paths:
          - node_modules/
          
      - run: npm run build-prod
      - run: npm run deploy --token=$FIREBASE_TOKEN --non-interactive
        
workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build