version: 2

# List of jobs
jobs:
  # The build job
  build:
    working_directory: ~/project
    docker:
      - image: "circleci/node:6.10-browsers"
    steps:
      # Steps to be added
      - checkout
      - run:
        name: Install firebase
        command: npm install -g firebase-tools
      - run:
        name: Install local dependencies
        command: npm install
      - run:
        name: Build
        command: npm run build-prod

  # The deploy job
  deploy:
    working_directory: ~/project
    docker:
      - image: "circleci/node:6.10-browsers"
    steps:
      # Steps to be added
      - checkout
      - run:
        name: Deploy
        command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
        
workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build
      - deploy