
version: 2

# List of jobs
jobs:
  # The build job
  build:
    working_directory: ~/project
    docker:
      - image: "circleci/node:latest"
    branches:
      ignore:
        - develop
    steps:
      # Steps to be added
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
      - run: sudo npm install -g npm@latest
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules/
      - run: npm run build-prod
      - run: npm run deploy --token=$FIREBASE_TOKEN --non-interactive
        
workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build
