version: 2

# List of jobs
jobs:
  # The build job
  build:
    filters:
      branches:
        only: master
    working_directory: ~/project
    docker:
      - image: "circleci/node:chakracore-10.13-browsers-legacy"
    steps:
      # Steps to be added
      - checkout
      - run: sudo npm install -g npm
      - run: npm install
      - run: npm rebuild node-sass
      - run: npm run build-prod
      - run: npm run deploy --token=$FIREBASE_TOKEN --non-interactive
        
workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build