version: 2

# List of jobs
jobs:
  # The build job
  build:
    working_directory: ~/project
    docker:
      - image: "circleci/node:6.10-browsers"
    steps:
      # Steps to be added
      - checkout
      - run: npm install
      - run: npm run build-prod
      - run: npm run deploy --token=$FIREBASE_TOKEN --non-interactive
        
workflows:
  version: 2
  # The build and deploy workflow
  build_and_deploy:
    jobs:
      - build